### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Struggle-lsl** [pfliu-nlp/Summarization-Features#1]
Hello, senior brother, after reading your previous paper on automatic generation of comments, can you share the code on how to extract pdf information to json structurally

**Comment by Struggle-lsl** [comment]
thanks

**Comment by pfliu-nlp** [comment]
Hi, are you referring to auto-review work? You can find the answer in the paper: 
![image](https://user-images.githubusercontent.com/59123869/211848029-135d61ea-68ba-4006-b9f3-5fb33f7f4ab8.png)
